spring:
  application:
    name: personal-finance
  datasource:
    url: jdbc:h2:file:${user.home}/.cauecalil-personal-finance-app/finance;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: false

server:
  address: 127.0.0.1
  port: 2560

logging:
  level:
    com.cauecalil: DEBUG
    org.hibernate.SQL: WARN

app:
  heartbeat:
    enabled: true
    timeout-ms: 25000
    monitor-delay-ms: 5000
    startup-grace-ms: 15000
  desktop:
    open-browser-on-startup: true
    startup-url: http://${server.address}:${server.port}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    try-it-out-enabled: true
  api-docs:
    path: /v3/api-docs
  show-actuator: false
